# Generated by Django 4.1.5 on 2023-01-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('daily_tasks', models.CharField(max_length=120)),
                ('completion', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('Monthly_tasks', models.CharField(max_length=120)),
                ('completion', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('Weekly_tasks', models.CharField(max_length=120)),
                ('completion', models.BooleanField(default=0)),
            ],
        ),
    ]
