# Generated by Django 4.1.5 on 2023-01-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('daily_tasks', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('Monthly_tasks', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('pass_word', models.CharField(max_length=20)),
                ('pass_word_confirm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('Weekly_tasks', models.CharField(max_length=120)),
            ],
        ),
    ]
