# Generated by Django 4.1.5 on 2023-01-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='completion',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='monthlytasks',
            name='completion',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='weeklytasks',
            name='completion',
            field=models.BooleanField(default=0),
        ),
    ]
