# Generated by Django 4.1.5 on 2023-01-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_dailytasks_completion_monthlytasks_completion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTasks',
        ),
        migrations.DeleteModel(
            name='MonthlyTasks',
        ),
        migrations.DeleteModel(
            name='WeeklyTasks',
        ),
    ]
