# Generated by Django 4.1.5 on 2023-01-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_dailytasks_delete_monthlytasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='current_user',
            field=models.BooleanField(default=False),
        ),
    ]
